<?xml version="1.0" encoding="utf-8"?><Database Name="HONK" Class="HONKDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\HONK.mdf;Integrated Security=True" SettingsObjectName="HONK.Properties.Settings" SettingsPropertyName="HONKDBContext" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Age" Member="Ages">
    <Type Name="Age">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Age_Contestant" Member="Contestants" ThisKey="id" OtherKey="age_id" Type="Contestant" />
    </Type>
  </Table>
  <Table Name="dbo.MasterScore" Member="MasterScores">
    <Type Name="MasterScore">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="contestant_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="palapala" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="interview" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="oli" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="music" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hula_auana" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_auana_deduction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_kahiko" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_kahiko_deduction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_palua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_palua_deduction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costume_auana" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costume_kahiko" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costume_palua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="out_of_order_deduction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Contestant_MasterScore" Member="Contestant" ThisKey="contestant_id" OtherKey="id" Type="Contestant" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Award" Member="Awards">
    <Type Name="Award">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Contestant" Member="Contestants">
    <Type Name="Contestant">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="age_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gender_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="division_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="halau_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="kumu_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="entry_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="entry_num_fri" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="entry_num_sat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Contestant_MasterScore" Member="MasterScores" ThisKey="id" OtherKey="contestant_id" Type="MasterScore" />
      <Association Name="Contestant_JudgeScore" Member="JudgeScores" ThisKey="id" OtherKey="contestant_id" Type="JudgeScore" />
      <Association Name="Age_Contestant" Member="Age" ThisKey="age_id" OtherKey="id" Type="Age" IsForeignKey="true" />
      <Association Name="Division_Contestant" Member="Division" ThisKey="division_id" OtherKey="id" Type="Division" IsForeignKey="true" />
      <Association Name="Gender_Contestant" Member="Gender" ThisKey="gender_id" OtherKey="id" Type="Gender" IsForeignKey="true" />
      <Association Name="Halau_Contestant" Member="Halau" ThisKey="halau_id" OtherKey="id" Type="Halau" IsForeignKey="true" />
      <Association Name="Kumu_Contestant" Member="Kumu" ThisKey="kumu_id" OtherKey="id" Type="Kumu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Division" Member="Divisions">
    <Type Name="Division">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Division_Contestant" Member="Contestants" ThisKey="id" OtherKey="division_id" Type="Contestant" />
    </Type>
  </Table>
  <Table Name="dbo.Gender" Member="Genders">
    <Type Name="Gender">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Gender_Contestant" Member="Contestants" ThisKey="id" OtherKey="gender_id" Type="Contestant" />
    </Type>
  </Table>
  <Table Name="dbo.Halau" Member="Halaus">
    <Type Name="Halau">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Halau_Contestant" Member="Contestants" ThisKey="id" OtherKey="halau_id" Type="Contestant" />
    </Type>
  </Table>
  <Table Name="dbo.Judge" Member="Judges">
    <Type Name="Judge">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Judge_JudgeScore" Member="JudgeScores" ThisKey="id" OtherKey="judge_id" Type="JudgeScore" />
    </Type>
  </Table>
  <Table Name="dbo.JudgeScore" Member="JudgeScores">
    <Type Name="JudgeScore">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="contestant_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="judge_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="interview" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costume_auana" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costume_kahiko" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costume_palua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_auana" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_kahiko" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_palua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Contestant_JudgeScore" Member="Contestant" ThisKey="contestant_id" OtherKey="id" Type="Contestant" IsForeignKey="true" />
      <Association Name="Judge_JudgeScore" Member="Judge" ThisKey="judge_id" OtherKey="id" Type="Judge" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Kumu" Member="Kumus">
    <Type Name="Kumu">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Kumu_Contestant" Member="Contestants" ThisKey="id" OtherKey="kumu_id" Type="Contestant" />
    </Type>
  </Table>
  <Table Name="dbo.vw_BreakingScore" Member="vw_BreakingScores">
    <Type Name="vw_BreakingScore">
      <Column Name="contestant_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="interview_tie" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costume_auana_tie" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costume_kahiko_tie" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costume_palua_tie" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_auana_tie" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_kahiko_tie" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_palua_tie" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_ContestantDetails" Member="vw_ContestantDetails">
    <Type Name="vw_ContestantDetail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="age_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="gender_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="division_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="halau_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="kumu_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="entry_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="entry_num_fri" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="entry_num_sat" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_BreakingScoreNet" Member="vw_BreakingScoreNets">
    <Type Name="vw_BreakingScoreNet">
      <Column Name="contestant_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="palapala" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="interview_tie" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="oli" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="hula_auana_net" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_kahiko_net" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_palua_net" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="out_of_order_deduction" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_MasterScoreDetails" Member="vw_MasterScoreDetails">
    <Type Name="vw_MasterScoreDetail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="entry_num_fri" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="entry_num_sat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="age_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="gender_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="division_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="interview" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="interview_tie" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="overall_score" Type="System.Decimal" DbType="Decimal(24,3)" CanBeNull="true" />
      <Column Name="overall_break_score" Type="System.Decimal" DbType="Decimal(22,3)" CanBeNull="true" />
      <Column Name="music" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="halau_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="kumu_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="entry_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_OverallBreakingScore" Member="vw_OverallBreakingScores">
    <Type Name="vw_OverallBreakingScore">
      <Column Name="contestant_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="combined_hula_score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="overall_break_score" Type="System.Decimal" DbType="Decimal(22,3)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_OverallScore" Member="vw_OverallScores">
    <Type Name="vw_OverallScore">
      <Column Name="contestant_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="interview" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="interview_tie" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="overall_score" Type="System.Decimal" DbType="Decimal(24,3)" CanBeNull="true" />
      <Column Name="overall_break_score" Type="System.Decimal" DbType="Decimal(22,3)" CanBeNull="true" />
      <Column Name="music" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="combined_hula_score" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_ContestantScoreDetails" Member="vw_ContestantScoreDetails">
    <Type Name="vw_ContestantScoreDetail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="judge_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="judge_score_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="master_score_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="age_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="gender_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="division_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="halau_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="kumu_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="entry_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="entry_num_fri" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="entry_num_sat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="judge_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="palapala" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="interview" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="oli" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="music" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_auana" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_auana_deduction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_kahiko" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_kahiko_deduction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_palua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_palua_deduction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costume_auana" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costume_kahiko" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costume_palua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="out_of_order_deduction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="judge_score_interview" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="judge_score_costume_auana" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="judge_score_costume_kahiko" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="judge_score_costume_palua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="judge_score_hula_auana" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="judge_score_hula_kahiko" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="judge_score_hula_palua" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Contestant_JudgeScore" Member="vw_Contestant_JudgeScores">
    <Type Name="vw_Contestant_JudgeScore">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="judge_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="age_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="gender_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="division_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="halau_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="kumu_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="entry_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="entry_num_fri" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="entry_num_sat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="interview" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costume_auana" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costume_kahiko" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costume_palua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_auana" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_kahiko" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hula_palua" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>