//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONK {
    
    
    public partial class HonkReports {
        
        /// <summary>
        /// EntryYearTb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox EntryYearTb;
        
        /// <summary>
        /// MasterGVUP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel MasterGVUP;
        
        /// <summary>
        /// MasterTabulationScore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HONK.Reports.MasterTabulationScore MasterTabulationScore;
        
        /// <summary>
        /// NonPaluaReptUP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel NonPaluaReptUP;
        
        /// <summary>
        /// ConstestantScoresReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HONK.Reports.ContestantTabulationScore ConstestantScoresReport;
        
        /// <summary>
        /// PaluaReptUP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel PaluaReptUP;
        
        /// <summary>
        /// ConstestantScoresPaluaReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HONK.Reports.ContestantScoresPalua_WUC ConstestantScoresPaluaReport;
    }
}
