#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONK
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HONK")]
	public partial class HONKDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAge(Age instance);
    partial void UpdateAge(Age instance);
    partial void DeleteAge(Age instance);
    partial void InsertScore(Score instance);
    partial void UpdateScore(Score instance);
    partial void DeleteScore(Score instance);
    partial void InsertContestant(Contestant instance);
    partial void UpdateContestant(Contestant instance);
    partial void DeleteContestant(Contestant instance);
    partial void InsertCostume(Costume instance);
    partial void UpdateCostume(Costume instance);
    partial void DeleteCostume(Costume instance);
    partial void InsertDivision(Division instance);
    partial void UpdateDivision(Division instance);
    partial void DeleteDivision(Division instance);
    partial void InsertGender(Gender instance);
    partial void UpdateGender(Gender instance);
    partial void DeleteGender(Gender instance);
    partial void InsertHalau(Halau instance);
    partial void UpdateHalau(Halau instance);
    partial void DeleteHalau(Halau instance);
    partial void InsertJudge(Judge instance);
    partial void UpdateJudge(Judge instance);
    partial void DeleteJudge(Judge instance);
    partial void InsertKumu(Kumu instance);
    partial void UpdateKumu(Kumu instance);
    partial void DeleteKumu(Kumu instance);
    partial void InsertMasterScore(MasterScore instance);
    partial void UpdateMasterScore(MasterScore instance);
    partial void DeleteMasterScore(MasterScore instance);
    #endregion
		
		public HONKDBDataContext() : 
				base(global::HONK.Properties.Settings.Default.HONKDBContext, mappingSource)
		{
			OnCreated();
		}
		
		public HONKDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HONKDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HONKDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HONKDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Age> Ages
		{
			get
			{
				return this.GetTable<Age>();
			}
		}
		
		public System.Data.Linq.Table<Score> Scores
		{
			get
			{
				return this.GetTable<Score>();
			}
		}
		
		public System.Data.Linq.Table<Contestant> Contestants
		{
			get
			{
				return this.GetTable<Contestant>();
			}
		}
		
		public System.Data.Linq.Table<Costume> Costumes
		{
			get
			{
				return this.GetTable<Costume>();
			}
		}
		
		public System.Data.Linq.Table<Division> Divisions
		{
			get
			{
				return this.GetTable<Division>();
			}
		}
		
		public System.Data.Linq.Table<Gender> Genders
		{
			get
			{
				return this.GetTable<Gender>();
			}
		}
		
		public System.Data.Linq.Table<Halau> Halaus
		{
			get
			{
				return this.GetTable<Halau>();
			}
		}
		
		public System.Data.Linq.Table<Judge> Judges
		{
			get
			{
				return this.GetTable<Judge>();
			}
		}
		
		public System.Data.Linq.Table<Kumu> Kumus
		{
			get
			{
				return this.GetTable<Kumu>();
			}
		}
		
		public System.Data.Linq.Table<MasterScore> MasterScores
		{
			get
			{
				return this.GetTable<MasterScore>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Age")]
	public partial class Age : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _age_id;
		
		private string _name;
		
		private EntitySet<Contestant> _Contestants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onage_idChanging(int value);
    partial void Onage_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Age()
		{
			this._Contestants = new EntitySet<Contestant>(new Action<Contestant>(this.attach_Contestants), new Action<Contestant>(this.detach_Contestants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int age_id
		{
			get
			{
				return this._age_id;
			}
			set
			{
				if ((this._age_id != value))
				{
					this.Onage_idChanging(value);
					this.SendPropertyChanging();
					this._age_id = value;
					this.SendPropertyChanged("age_id");
					this.Onage_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Age_Contestant", Storage="_Contestants", ThisKey="age_id", OtherKey="age_age_id")]
		public EntitySet<Contestant> Contestants
		{
			get
			{
				return this._Contestants;
			}
			set
			{
				this._Contestants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Age = this;
		}
		
		private void detach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Age = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Score")]
	public partial class Score : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _score_id;
		
		private int _judge_judges_id;
		
		private int _contestant_contestant_id;
		
		private decimal _interview;
		
		private decimal _oli;
		
		private decimal _auana;
		
		private decimal _kahiko;
		
		private decimal _music;
		
		private decimal _auana_costume;
		
		private decimal _kahiko_costume;
		
		private decimal _palapala;
		
		private EntityRef<Contestant> _Contestant;
		
		private EntityRef<Judge> _Judge;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onscore_idChanging(int value);
    partial void Onscore_idChanged();
    partial void Onjudge_judges_idChanging(int value);
    partial void Onjudge_judges_idChanged();
    partial void Oncontestant_contestant_idChanging(int value);
    partial void Oncontestant_contestant_idChanged();
    partial void OninterviewChanging(decimal value);
    partial void OninterviewChanged();
    partial void OnoliChanging(decimal value);
    partial void OnoliChanged();
    partial void OnauanaChanging(decimal value);
    partial void OnauanaChanged();
    partial void OnkahikoChanging(decimal value);
    partial void OnkahikoChanged();
    partial void OnmusicChanging(decimal value);
    partial void OnmusicChanged();
    partial void Onauana_costumeChanging(decimal value);
    partial void Onauana_costumeChanged();
    partial void Onkahiko_costumeChanging(decimal value);
    partial void Onkahiko_costumeChanged();
    partial void OnpalapalaChanging(decimal value);
    partial void OnpalapalaChanged();
    #endregion
		
		public Score()
		{
			this._Contestant = default(EntityRef<Contestant>);
			this._Judge = default(EntityRef<Judge>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_score_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int score_id
		{
			get
			{
				return this._score_id;
			}
			set
			{
				if ((this._score_id != value))
				{
					this.Onscore_idChanging(value);
					this.SendPropertyChanging();
					this._score_id = value;
					this.SendPropertyChanged("score_id");
					this.Onscore_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_judge_judges_id", DbType="Int NOT NULL")]
		public int judge_judges_id
		{
			get
			{
				return this._judge_judges_id;
			}
			set
			{
				if ((this._judge_judges_id != value))
				{
					if (this._Judge.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onjudge_judges_idChanging(value);
					this.SendPropertyChanging();
					this._judge_judges_id = value;
					this.SendPropertyChanged("judge_judges_id");
					this.Onjudge_judges_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contestant_contestant_id", DbType="Int NOT NULL")]
		public int contestant_contestant_id
		{
			get
			{
				return this._contestant_contestant_id;
			}
			set
			{
				if ((this._contestant_contestant_id != value))
				{
					if (this._Contestant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncontestant_contestant_idChanging(value);
					this.SendPropertyChanging();
					this._contestant_contestant_id = value;
					this.SendPropertyChanged("contestant_contestant_id");
					this.Oncontestant_contestant_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_interview", DbType="Decimal(18,0) NOT NULL")]
		public decimal interview
		{
			get
			{
				return this._interview;
			}
			set
			{
				if ((this._interview != value))
				{
					this.OninterviewChanging(value);
					this.SendPropertyChanging();
					this._interview = value;
					this.SendPropertyChanged("interview");
					this.OninterviewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oli", DbType="Decimal(18,0) NOT NULL")]
		public decimal oli
		{
			get
			{
				return this._oli;
			}
			set
			{
				if ((this._oli != value))
				{
					this.OnoliChanging(value);
					this.SendPropertyChanging();
					this._oli = value;
					this.SendPropertyChanged("oli");
					this.OnoliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auana", DbType="Decimal(18,0) NOT NULL")]
		public decimal auana
		{
			get
			{
				return this._auana;
			}
			set
			{
				if ((this._auana != value))
				{
					this.OnauanaChanging(value);
					this.SendPropertyChanging();
					this._auana = value;
					this.SendPropertyChanged("auana");
					this.OnauanaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kahiko", DbType="Decimal(18,0) NOT NULL")]
		public decimal kahiko
		{
			get
			{
				return this._kahiko;
			}
			set
			{
				if ((this._kahiko != value))
				{
					this.OnkahikoChanging(value);
					this.SendPropertyChanging();
					this._kahiko = value;
					this.SendPropertyChanged("kahiko");
					this.OnkahikoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_music", DbType="Decimal(18,0) NOT NULL")]
		public decimal music
		{
			get
			{
				return this._music;
			}
			set
			{
				if ((this._music != value))
				{
					this.OnmusicChanging(value);
					this.SendPropertyChanging();
					this._music = value;
					this.SendPropertyChanged("music");
					this.OnmusicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auana_costume", DbType="Decimal(18,0) NOT NULL")]
		public decimal auana_costume
		{
			get
			{
				return this._auana_costume;
			}
			set
			{
				if ((this._auana_costume != value))
				{
					this.Onauana_costumeChanging(value);
					this.SendPropertyChanging();
					this._auana_costume = value;
					this.SendPropertyChanged("auana_costume");
					this.Onauana_costumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kahiko_costume", DbType="Decimal(18,0) NOT NULL")]
		public decimal kahiko_costume
		{
			get
			{
				return this._kahiko_costume;
			}
			set
			{
				if ((this._kahiko_costume != value))
				{
					this.Onkahiko_costumeChanging(value);
					this.SendPropertyChanging();
					this._kahiko_costume = value;
					this.SendPropertyChanged("kahiko_costume");
					this.Onkahiko_costumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palapala", DbType="Decimal(18,0) NOT NULL")]
		public decimal palapala
		{
			get
			{
				return this._palapala;
			}
			set
			{
				if ((this._palapala != value))
				{
					this.OnpalapalaChanging(value);
					this.SendPropertyChanging();
					this._palapala = value;
					this.SendPropertyChanged("palapala");
					this.OnpalapalaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contestant_Score", Storage="_Contestant", ThisKey="contestant_contestant_id", OtherKey="contestant_id", IsForeignKey=true)]
		public Contestant Contestant
		{
			get
			{
				return this._Contestant.Entity;
			}
			set
			{
				Contestant previousValue = this._Contestant.Entity;
				if (((previousValue != value) 
							|| (this._Contestant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Contestant.Entity = null;
						previousValue.Scores.Remove(this);
					}
					this._Contestant.Entity = value;
					if ((value != null))
					{
						value.Scores.Add(this);
						this._contestant_contestant_id = value.contestant_id;
					}
					else
					{
						this._contestant_contestant_id = default(int);
					}
					this.SendPropertyChanged("Contestant");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Judge_Score", Storage="_Judge", ThisKey="judge_judges_id", OtherKey="judge_id", IsForeignKey=true)]
		public Judge Judge
		{
			get
			{
				return this._Judge.Entity;
			}
			set
			{
				Judge previousValue = this._Judge.Entity;
				if (((previousValue != value) 
							|| (this._Judge.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Judge.Entity = null;
						previousValue.Scores.Remove(this);
					}
					this._Judge.Entity = value;
					if ((value != null))
					{
						value.Scores.Add(this);
						this._judge_judges_id = value.judge_id;
					}
					else
					{
						this._judge_judges_id = default(int);
					}
					this.SendPropertyChanged("Judge");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contestant")]
	public partial class Contestant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _contestant_id;
		
		private int _age_age_id;
		
		private int _gender_gender_id;
		
		private int _division_division_id;
		
		private int _halau_halua_id;
		
		private int _kumu_kumu_id;
		
		private string _first_name;
		
		private string _last_name;
		
		private System.DateTime _entry_date;
		
		private EntitySet<Score> _Scores;
		
		private EntitySet<MasterScore> _MasterScores;
		
		private EntityRef<Age> _Age;
		
		private EntityRef<Division> _Division;
		
		private EntityRef<Gender> _Gender;
		
		private EntityRef<Halau> _Halau;
		
		private EntityRef<Kumu> _Kumu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncontestant_idChanging(int value);
    partial void Oncontestant_idChanged();
    partial void Onage_age_idChanging(int value);
    partial void Onage_age_idChanged();
    partial void Ongender_gender_idChanging(int value);
    partial void Ongender_gender_idChanged();
    partial void Ondivision_division_idChanging(int value);
    partial void Ondivision_division_idChanged();
    partial void Onhalau_halua_idChanging(int value);
    partial void Onhalau_halua_idChanged();
    partial void Onkumu_kumu_idChanging(int value);
    partial void Onkumu_kumu_idChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void Onentry_dateChanging(System.DateTime value);
    partial void Onentry_dateChanged();
    #endregion
		
		public Contestant()
		{
			this._Scores = new EntitySet<Score>(new Action<Score>(this.attach_Scores), new Action<Score>(this.detach_Scores));
			this._MasterScores = new EntitySet<MasterScore>(new Action<MasterScore>(this.attach_MasterScores), new Action<MasterScore>(this.detach_MasterScores));
			this._Age = default(EntityRef<Age>);
			this._Division = default(EntityRef<Division>);
			this._Gender = default(EntityRef<Gender>);
			this._Halau = default(EntityRef<Halau>);
			this._Kumu = default(EntityRef<Kumu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contestant_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int contestant_id
		{
			get
			{
				return this._contestant_id;
			}
			set
			{
				if ((this._contestant_id != value))
				{
					this.Oncontestant_idChanging(value);
					this.SendPropertyChanging();
					this._contestant_id = value;
					this.SendPropertyChanged("contestant_id");
					this.Oncontestant_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age_age_id", DbType="Int NOT NULL")]
		public int age_age_id
		{
			get
			{
				return this._age_age_id;
			}
			set
			{
				if ((this._age_age_id != value))
				{
					if (this._Age.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onage_age_idChanging(value);
					this.SendPropertyChanging();
					this._age_age_id = value;
					this.SendPropertyChanged("age_age_id");
					this.Onage_age_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender_gender_id", DbType="Int NOT NULL")]
		public int gender_gender_id
		{
			get
			{
				return this._gender_gender_id;
			}
			set
			{
				if ((this._gender_gender_id != value))
				{
					if (this._Gender.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongender_gender_idChanging(value);
					this.SendPropertyChanging();
					this._gender_gender_id = value;
					this.SendPropertyChanged("gender_gender_id");
					this.Ongender_gender_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_division_division_id", DbType="Int NOT NULL")]
		public int division_division_id
		{
			get
			{
				return this._division_division_id;
			}
			set
			{
				if ((this._division_division_id != value))
				{
					if (this._Division.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondivision_division_idChanging(value);
					this.SendPropertyChanging();
					this._division_division_id = value;
					this.SendPropertyChanged("division_division_id");
					this.Ondivision_division_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_halau_halua_id", DbType="Int NOT NULL")]
		public int halau_halua_id
		{
			get
			{
				return this._halau_halua_id;
			}
			set
			{
				if ((this._halau_halua_id != value))
				{
					if (this._Halau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onhalau_halua_idChanging(value);
					this.SendPropertyChanging();
					this._halau_halua_id = value;
					this.SendPropertyChanged("halau_halua_id");
					this.Onhalau_halua_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumu_kumu_id", DbType="Int NOT NULL")]
		public int kumu_kumu_id
		{
			get
			{
				return this._kumu_kumu_id;
			}
			set
			{
				if ((this._kumu_kumu_id != value))
				{
					if (this._Kumu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkumu_kumu_idChanging(value);
					this.SendPropertyChanging();
					this._kumu_kumu_id = value;
					this.SendPropertyChanged("kumu_kumu_id");
					this.Onkumu_kumu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this.Onfirst_nameChanging(value);
					this.SendPropertyChanging();
					this._first_name = value;
					this.SendPropertyChanged("first_name");
					this.Onfirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entry_date", DbType="Date NOT NULL")]
		public System.DateTime entry_date
		{
			get
			{
				return this._entry_date;
			}
			set
			{
				if ((this._entry_date != value))
				{
					this.Onentry_dateChanging(value);
					this.SendPropertyChanging();
					this._entry_date = value;
					this.SendPropertyChanged("entry_date");
					this.Onentry_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contestant_Score", Storage="_Scores", ThisKey="contestant_id", OtherKey="contestant_contestant_id")]
		public EntitySet<Score> Scores
		{
			get
			{
				return this._Scores;
			}
			set
			{
				this._Scores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contestant_MasterScore", Storage="_MasterScores", ThisKey="contestant_id", OtherKey="contestants_contestant_id")]
		public EntitySet<MasterScore> MasterScores
		{
			get
			{
				return this._MasterScores;
			}
			set
			{
				this._MasterScores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Age_Contestant", Storage="_Age", ThisKey="age_age_id", OtherKey="age_id", IsForeignKey=true)]
		public Age Age
		{
			get
			{
				return this._Age.Entity;
			}
			set
			{
				Age previousValue = this._Age.Entity;
				if (((previousValue != value) 
							|| (this._Age.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Age.Entity = null;
						previousValue.Contestants.Remove(this);
					}
					this._Age.Entity = value;
					if ((value != null))
					{
						value.Contestants.Add(this);
						this._age_age_id = value.age_id;
					}
					else
					{
						this._age_age_id = default(int);
					}
					this.SendPropertyChanged("Age");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Division_Contestant", Storage="_Division", ThisKey="division_division_id", OtherKey="division_id", IsForeignKey=true)]
		public Division Division
		{
			get
			{
				return this._Division.Entity;
			}
			set
			{
				Division previousValue = this._Division.Entity;
				if (((previousValue != value) 
							|| (this._Division.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Division.Entity = null;
						previousValue.Contestants.Remove(this);
					}
					this._Division.Entity = value;
					if ((value != null))
					{
						value.Contestants.Add(this);
						this._division_division_id = value.division_id;
					}
					else
					{
						this._division_division_id = default(int);
					}
					this.SendPropertyChanged("Division");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gender_Contestant", Storage="_Gender", ThisKey="gender_gender_id", OtherKey="gender_id", IsForeignKey=true)]
		public Gender Gender
		{
			get
			{
				return this._Gender.Entity;
			}
			set
			{
				Gender previousValue = this._Gender.Entity;
				if (((previousValue != value) 
							|| (this._Gender.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Gender.Entity = null;
						previousValue.Contestants.Remove(this);
					}
					this._Gender.Entity = value;
					if ((value != null))
					{
						value.Contestants.Add(this);
						this._gender_gender_id = value.gender_id;
					}
					else
					{
						this._gender_gender_id = default(int);
					}
					this.SendPropertyChanged("Gender");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Halau_Contestant", Storage="_Halau", ThisKey="halau_halua_id", OtherKey="halua_id", IsForeignKey=true)]
		public Halau Halau
		{
			get
			{
				return this._Halau.Entity;
			}
			set
			{
				Halau previousValue = this._Halau.Entity;
				if (((previousValue != value) 
							|| (this._Halau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Halau.Entity = null;
						previousValue.Contestants.Remove(this);
					}
					this._Halau.Entity = value;
					if ((value != null))
					{
						value.Contestants.Add(this);
						this._halau_halua_id = value.halua_id;
					}
					else
					{
						this._halau_halua_id = default(int);
					}
					this.SendPropertyChanged("Halau");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kumu_Contestant", Storage="_Kumu", ThisKey="kumu_kumu_id", OtherKey="kumu_id", IsForeignKey=true)]
		public Kumu Kumu
		{
			get
			{
				return this._Kumu.Entity;
			}
			set
			{
				Kumu previousValue = this._Kumu.Entity;
				if (((previousValue != value) 
							|| (this._Kumu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kumu.Entity = null;
						previousValue.Contestants.Remove(this);
					}
					this._Kumu.Entity = value;
					if ((value != null))
					{
						value.Contestants.Add(this);
						this._kumu_kumu_id = value.kumu_id;
					}
					else
					{
						this._kumu_kumu_id = default(int);
					}
					this.SendPropertyChanged("Kumu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Scores(Score entity)
		{
			this.SendPropertyChanging();
			entity.Contestant = this;
		}
		
		private void detach_Scores(Score entity)
		{
			this.SendPropertyChanging();
			entity.Contestant = null;
		}
		
		private void attach_MasterScores(MasterScore entity)
		{
			this.SendPropertyChanging();
			entity.Contestant = this;
		}
		
		private void detach_MasterScores(MasterScore entity)
		{
			this.SendPropertyChanging();
			entity.Contestant = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Costume")]
	public partial class Costume : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _costume_id;
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncostume_idChanging(int value);
    partial void Oncostume_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Costume()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costume_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int costume_id
		{
			get
			{
				return this._costume_id;
			}
			set
			{
				if ((this._costume_id != value))
				{
					this.Oncostume_idChanging(value);
					this.SendPropertyChanging();
					this._costume_id = value;
					this.SendPropertyChanged("costume_id");
					this.Oncostume_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Division")]
	public partial class Division : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _division_id;
		
		private string _name;
		
		private EntitySet<Contestant> _Contestants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondivision_idChanging(int value);
    partial void Ondivision_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Division()
		{
			this._Contestants = new EntitySet<Contestant>(new Action<Contestant>(this.attach_Contestants), new Action<Contestant>(this.detach_Contestants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_division_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int division_id
		{
			get
			{
				return this._division_id;
			}
			set
			{
				if ((this._division_id != value))
				{
					this.Ondivision_idChanging(value);
					this.SendPropertyChanging();
					this._division_id = value;
					this.SendPropertyChanged("division_id");
					this.Ondivision_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Division_Contestant", Storage="_Contestants", ThisKey="division_id", OtherKey="division_division_id")]
		public EntitySet<Contestant> Contestants
		{
			get
			{
				return this._Contestants;
			}
			set
			{
				this._Contestants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Division = this;
		}
		
		private void detach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Division = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gender")]
	public partial class Gender : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _gender_id;
		
		private string _name;
		
		private EntitySet<Contestant> _Contestants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongender_idChanging(int value);
    partial void Ongender_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Gender()
		{
			this._Contestants = new EntitySet<Contestant>(new Action<Contestant>(this.attach_Contestants), new Action<Contestant>(this.detach_Contestants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int gender_id
		{
			get
			{
				return this._gender_id;
			}
			set
			{
				if ((this._gender_id != value))
				{
					this.Ongender_idChanging(value);
					this.SendPropertyChanging();
					this._gender_id = value;
					this.SendPropertyChanged("gender_id");
					this.Ongender_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gender_Contestant", Storage="_Contestants", ThisKey="gender_id", OtherKey="gender_gender_id")]
		public EntitySet<Contestant> Contestants
		{
			get
			{
				return this._Contestants;
			}
			set
			{
				this._Contestants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Gender = this;
		}
		
		private void detach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Gender = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Halau")]
	public partial class Halau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _halua_id;
		
		private string _name;
		
		private EntitySet<Contestant> _Contestants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhalua_idChanging(int value);
    partial void Onhalua_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Halau()
		{
			this._Contestants = new EntitySet<Contestant>(new Action<Contestant>(this.attach_Contestants), new Action<Contestant>(this.detach_Contestants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_halua_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int halua_id
		{
			get
			{
				return this._halua_id;
			}
			set
			{
				if ((this._halua_id != value))
				{
					this.Onhalua_idChanging(value);
					this.SendPropertyChanging();
					this._halua_id = value;
					this.SendPropertyChanged("halua_id");
					this.Onhalua_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Halau_Contestant", Storage="_Contestants", ThisKey="halua_id", OtherKey="halau_halua_id")]
		public EntitySet<Contestant> Contestants
		{
			get
			{
				return this._Contestants;
			}
			set
			{
				this._Contestants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Halau = this;
		}
		
		private void detach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Halau = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Judge")]
	public partial class Judge : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _judge_id;
		
		private string _first_name;
		
		private string _last_name;
		
		private EntitySet<Score> _Scores;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onjudge_idChanging(int value);
    partial void Onjudge_idChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    #endregion
		
		public Judge()
		{
			this._Scores = new EntitySet<Score>(new Action<Score>(this.attach_Scores), new Action<Score>(this.detach_Scores));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_judge_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int judge_id
		{
			get
			{
				return this._judge_id;
			}
			set
			{
				if ((this._judge_id != value))
				{
					this.Onjudge_idChanging(value);
					this.SendPropertyChanging();
					this._judge_id = value;
					this.SendPropertyChanged("judge_id");
					this.Onjudge_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this.Onfirst_nameChanging(value);
					this.SendPropertyChanging();
					this._first_name = value;
					this.SendPropertyChanged("first_name");
					this.Onfirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Judge_Score", Storage="_Scores", ThisKey="judge_id", OtherKey="judge_judges_id")]
		public EntitySet<Score> Scores
		{
			get
			{
				return this._Scores;
			}
			set
			{
				this._Scores.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Scores(Score entity)
		{
			this.SendPropertyChanging();
			entity.Judge = this;
		}
		
		private void detach_Scores(Score entity)
		{
			this.SendPropertyChanging();
			entity.Judge = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kumu")]
	public partial class Kumu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kumu_id;
		
		private string _first_name;
		
		private string _last_name;
		
		private EntitySet<Contestant> _Contestants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkumu_idChanging(int value);
    partial void Onkumu_idChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    #endregion
		
		public Kumu()
		{
			this._Contestants = new EntitySet<Contestant>(new Action<Contestant>(this.attach_Contestants), new Action<Contestant>(this.detach_Contestants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kumu_id
		{
			get
			{
				return this._kumu_id;
			}
			set
			{
				if ((this._kumu_id != value))
				{
					this.Onkumu_idChanging(value);
					this.SendPropertyChanging();
					this._kumu_id = value;
					this.SendPropertyChanged("kumu_id");
					this.Onkumu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this.Onfirst_nameChanging(value);
					this.SendPropertyChanging();
					this._first_name = value;
					this.SendPropertyChanged("first_name");
					this.Onfirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kumu_Contestant", Storage="_Contestants", ThisKey="kumu_id", OtherKey="kumu_kumu_id")]
		public EntitySet<Contestant> Contestants
		{
			get
			{
				return this._Contestants;
			}
			set
			{
				this._Contestants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Kumu = this;
		}
		
		private void detach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Kumu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MasterScore")]
	public partial class MasterScore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _masterscores_id;
		
		private int _contestants_contestant_id;
		
		private int _interview;
		
		private int _auana_costume;
		
		private int _kahiko_costume;
		
		private decimal _oli;
		
		private int _hula;
		
		private int _overall;
		
		private int _music;
		
		private EntityRef<Contestant> _Contestant;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmasterscores_idChanging(int value);
    partial void Onmasterscores_idChanged();
    partial void Oncontestants_contestant_idChanging(int value);
    partial void Oncontestants_contestant_idChanged();
    partial void OninterviewChanging(int value);
    partial void OninterviewChanged();
    partial void Onauana_costumeChanging(int value);
    partial void Onauana_costumeChanged();
    partial void Onkahiko_costumeChanging(int value);
    partial void Onkahiko_costumeChanged();
    partial void OnoliChanging(decimal value);
    partial void OnoliChanged();
    partial void OnhulaChanging(int value);
    partial void OnhulaChanged();
    partial void OnoverallChanging(int value);
    partial void OnoverallChanged();
    partial void OnmusicChanging(int value);
    partial void OnmusicChanged();
    #endregion
		
		public MasterScore()
		{
			this._Contestant = default(EntityRef<Contestant>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masterscores_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int masterscores_id
		{
			get
			{
				return this._masterscores_id;
			}
			set
			{
				if ((this._masterscores_id != value))
				{
					this.Onmasterscores_idChanging(value);
					this.SendPropertyChanging();
					this._masterscores_id = value;
					this.SendPropertyChanged("masterscores_id");
					this.Onmasterscores_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contestants_contestant_id", DbType="Int NOT NULL")]
		public int contestants_contestant_id
		{
			get
			{
				return this._contestants_contestant_id;
			}
			set
			{
				if ((this._contestants_contestant_id != value))
				{
					if (this._Contestant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncontestants_contestant_idChanging(value);
					this.SendPropertyChanging();
					this._contestants_contestant_id = value;
					this.SendPropertyChanged("contestants_contestant_id");
					this.Oncontestants_contestant_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_interview", DbType="Int NOT NULL")]
		public int interview
		{
			get
			{
				return this._interview;
			}
			set
			{
				if ((this._interview != value))
				{
					this.OninterviewChanging(value);
					this.SendPropertyChanging();
					this._interview = value;
					this.SendPropertyChanged("interview");
					this.OninterviewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auana_costume", DbType="Int NOT NULL")]
		public int auana_costume
		{
			get
			{
				return this._auana_costume;
			}
			set
			{
				if ((this._auana_costume != value))
				{
					this.Onauana_costumeChanging(value);
					this.SendPropertyChanging();
					this._auana_costume = value;
					this.SendPropertyChanged("auana_costume");
					this.Onauana_costumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kahiko_costume", DbType="Int NOT NULL")]
		public int kahiko_costume
		{
			get
			{
				return this._kahiko_costume;
			}
			set
			{
				if ((this._kahiko_costume != value))
				{
					this.Onkahiko_costumeChanging(value);
					this.SendPropertyChanging();
					this._kahiko_costume = value;
					this.SendPropertyChanged("kahiko_costume");
					this.Onkahiko_costumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oli", DbType="Decimal(18,0) NOT NULL")]
		public decimal oli
		{
			get
			{
				return this._oli;
			}
			set
			{
				if ((this._oli != value))
				{
					this.OnoliChanging(value);
					this.SendPropertyChanging();
					this._oli = value;
					this.SendPropertyChanged("oli");
					this.OnoliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula", DbType="Int NOT NULL")]
		public int hula
		{
			get
			{
				return this._hula;
			}
			set
			{
				if ((this._hula != value))
				{
					this.OnhulaChanging(value);
					this.SendPropertyChanging();
					this._hula = value;
					this.SendPropertyChanged("hula");
					this.OnhulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overall", DbType="Int NOT NULL")]
		public int overall
		{
			get
			{
				return this._overall;
			}
			set
			{
				if ((this._overall != value))
				{
					this.OnoverallChanging(value);
					this.SendPropertyChanging();
					this._overall = value;
					this.SendPropertyChanged("overall");
					this.OnoverallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_music", DbType="Int NOT NULL")]
		public int music
		{
			get
			{
				return this._music;
			}
			set
			{
				if ((this._music != value))
				{
					this.OnmusicChanging(value);
					this.SendPropertyChanging();
					this._music = value;
					this.SendPropertyChanged("music");
					this.OnmusicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contestant_MasterScore", Storage="_Contestant", ThisKey="contestants_contestant_id", OtherKey="contestant_id", IsForeignKey=true)]
		public Contestant Contestant
		{
			get
			{
				return this._Contestant.Entity;
			}
			set
			{
				Contestant previousValue = this._Contestant.Entity;
				if (((previousValue != value) 
							|| (this._Contestant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Contestant.Entity = null;
						previousValue.MasterScores.Remove(this);
					}
					this._Contestant.Entity = value;
					if ((value != null))
					{
						value.MasterScores.Add(this);
						this._contestants_contestant_id = value.contestant_id;
					}
					else
					{
						this._contestants_contestant_id = default(int);
					}
					this.SendPropertyChanged("Contestant");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
