#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONK
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HONK")]
	public partial class HONKDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAge(Age instance);
    partial void UpdateAge(Age instance);
    partial void DeleteAge(Age instance);
    partial void InsertMasterScore(MasterScore instance);
    partial void UpdateMasterScore(MasterScore instance);
    partial void DeleteMasterScore(MasterScore instance);
    partial void InsertAward(Award instance);
    partial void UpdateAward(Award instance);
    partial void DeleteAward(Award instance);
    partial void InsertContestant(Contestant instance);
    partial void UpdateContestant(Contestant instance);
    partial void DeleteContestant(Contestant instance);
    partial void InsertDivision(Division instance);
    partial void UpdateDivision(Division instance);
    partial void DeleteDivision(Division instance);
    partial void InsertGender(Gender instance);
    partial void UpdateGender(Gender instance);
    partial void DeleteGender(Gender instance);
    partial void InsertHalau(Halau instance);
    partial void UpdateHalau(Halau instance);
    partial void DeleteHalau(Halau instance);
    partial void InsertJudge(Judge instance);
    partial void UpdateJudge(Judge instance);
    partial void DeleteJudge(Judge instance);
    partial void InsertJudgeScore(JudgeScore instance);
    partial void UpdateJudgeScore(JudgeScore instance);
    partial void DeleteJudgeScore(JudgeScore instance);
    partial void InsertKumu(Kumu instance);
    partial void UpdateKumu(Kumu instance);
    partial void DeleteKumu(Kumu instance);
    #endregion
		
		public HONKDBDataContext() : 
				base(global::HONK.Properties.Settings.Default.HONKDBContext, mappingSource)
		{
			OnCreated();
		}
		
		public HONKDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HONKDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HONKDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HONKDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Age> Ages
		{
			get
			{
				return this.GetTable<Age>();
			}
		}
		
		public System.Data.Linq.Table<MasterScore> MasterScores
		{
			get
			{
				return this.GetTable<MasterScore>();
			}
		}
		
		public System.Data.Linq.Table<Award> Awards
		{
			get
			{
				return this.GetTable<Award>();
			}
		}
		
		public System.Data.Linq.Table<Contestant> Contestants
		{
			get
			{
				return this.GetTable<Contestant>();
			}
		}
		
		public System.Data.Linq.Table<Division> Divisions
		{
			get
			{
				return this.GetTable<Division>();
			}
		}
		
		public System.Data.Linq.Table<Gender> Genders
		{
			get
			{
				return this.GetTable<Gender>();
			}
		}
		
		public System.Data.Linq.Table<Halau> Halaus
		{
			get
			{
				return this.GetTable<Halau>();
			}
		}
		
		public System.Data.Linq.Table<Judge> Judges
		{
			get
			{
				return this.GetTable<Judge>();
			}
		}
		
		public System.Data.Linq.Table<JudgeScore> JudgeScores
		{
			get
			{
				return this.GetTable<JudgeScore>();
			}
		}
		
		public System.Data.Linq.Table<Kumu> Kumus
		{
			get
			{
				return this.GetTable<Kumu>();
			}
		}
		
		public System.Data.Linq.Table<vw_BreakingScore> vw_BreakingScores
		{
			get
			{
				return this.GetTable<vw_BreakingScore>();
			}
		}
		
		public System.Data.Linq.Table<vw_ContestantDetail> vw_ContestantDetails
		{
			get
			{
				return this.GetTable<vw_ContestantDetail>();
			}
		}
		
		public System.Data.Linq.Table<vw_BreakingScoreNet> vw_BreakingScoreNets
		{
			get
			{
				return this.GetTable<vw_BreakingScoreNet>();
			}
		}
		
		public System.Data.Linq.Table<vw_MasterScoreDetail> vw_MasterScoreDetails
		{
			get
			{
				return this.GetTable<vw_MasterScoreDetail>();
			}
		}
		
		public System.Data.Linq.Table<vw_OverallBreakingScore> vw_OverallBreakingScores
		{
			get
			{
				return this.GetTable<vw_OverallBreakingScore>();
			}
		}
		
		public System.Data.Linq.Table<vw_OverallScore> vw_OverallScores
		{
			get
			{
				return this.GetTable<vw_OverallScore>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Age")]
	public partial class Age : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private EntitySet<Contestant> _Contestants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Age()
		{
			this._Contestants = new EntitySet<Contestant>(new Action<Contestant>(this.attach_Contestants), new Action<Contestant>(this.detach_Contestants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Age_Contestant", Storage="_Contestants", ThisKey="id", OtherKey="age_id")]
		public EntitySet<Contestant> Contestants
		{
			get
			{
				return this._Contestants;
			}
			set
			{
				this._Contestants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Age = this;
		}
		
		private void detach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Age = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MasterScore")]
	public partial class MasterScore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _contestant_id;
		
		private int _palapala;
		
		private System.Nullable<int> _interview;
		
		private System.Nullable<decimal> _oli;
		
		private int _music;
		
		private System.Nullable<int> _hula_auana;
		
		private System.Nullable<int> _hula_auana_deduction;
		
		private System.Nullable<int> _hula_kahiko;
		
		private System.Nullable<int> _hula_kahiko_deduction;
		
		private System.Nullable<int> _hula_palua;
		
		private System.Nullable<int> _hula_palua_deduction;
		
		private System.Nullable<int> _costume_auana;
		
		private System.Nullable<int> _costume_kahiko;
		
		private System.Nullable<int> _costume_palua;
		
		private System.Nullable<int> _out_of_order_deduction;
		
		private EntityRef<Contestant> _Contestant;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncontestant_idChanging(int value);
    partial void Oncontestant_idChanged();
    partial void OnpalapalaChanging(int value);
    partial void OnpalapalaChanged();
    partial void OninterviewChanging(System.Nullable<int> value);
    partial void OninterviewChanged();
    partial void OnoliChanging(System.Nullable<decimal> value);
    partial void OnoliChanged();
    partial void OnmusicChanging(int value);
    partial void OnmusicChanged();
    partial void Onhula_auanaChanging(System.Nullable<int> value);
    partial void Onhula_auanaChanged();
    partial void Onhula_auana_deductionChanging(System.Nullable<int> value);
    partial void Onhula_auana_deductionChanged();
    partial void Onhula_kahikoChanging(System.Nullable<int> value);
    partial void Onhula_kahikoChanged();
    partial void Onhula_kahiko_deductionChanging(System.Nullable<int> value);
    partial void Onhula_kahiko_deductionChanged();
    partial void Onhula_paluaChanging(System.Nullable<int> value);
    partial void Onhula_paluaChanged();
    partial void Onhula_palua_deductionChanging(System.Nullable<int> value);
    partial void Onhula_palua_deductionChanged();
    partial void Oncostume_auanaChanging(System.Nullable<int> value);
    partial void Oncostume_auanaChanged();
    partial void Oncostume_kahikoChanging(System.Nullable<int> value);
    partial void Oncostume_kahikoChanged();
    partial void Oncostume_paluaChanging(System.Nullable<int> value);
    partial void Oncostume_paluaChanged();
    partial void Onout_of_order_deductionChanging(System.Nullable<int> value);
    partial void Onout_of_order_deductionChanged();
    #endregion
		
		public MasterScore()
		{
			this._Contestant = default(EntityRef<Contestant>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contestant_id", DbType="Int NOT NULL")]
		public int contestant_id
		{
			get
			{
				return this._contestant_id;
			}
			set
			{
				if ((this._contestant_id != value))
				{
					if (this._Contestant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncontestant_idChanging(value);
					this.SendPropertyChanging();
					this._contestant_id = value;
					this.SendPropertyChanged("contestant_id");
					this.Oncontestant_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palapala", DbType="Int NOT NULL")]
		public int palapala
		{
			get
			{
				return this._palapala;
			}
			set
			{
				if ((this._palapala != value))
				{
					this.OnpalapalaChanging(value);
					this.SendPropertyChanging();
					this._palapala = value;
					this.SendPropertyChanged("palapala");
					this.OnpalapalaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_interview", DbType="Int")]
		public System.Nullable<int> interview
		{
			get
			{
				return this._interview;
			}
			set
			{
				if ((this._interview != value))
				{
					this.OninterviewChanging(value);
					this.SendPropertyChanging();
					this._interview = value;
					this.SendPropertyChanged("interview");
					this.OninterviewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oli", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> oli
		{
			get
			{
				return this._oli;
			}
			set
			{
				if ((this._oli != value))
				{
					this.OnoliChanging(value);
					this.SendPropertyChanging();
					this._oli = value;
					this.SendPropertyChanged("oli");
					this.OnoliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_music", DbType="Int NOT NULL")]
		public int music
		{
			get
			{
				return this._music;
			}
			set
			{
				if ((this._music != value))
				{
					this.OnmusicChanging(value);
					this.SendPropertyChanging();
					this._music = value;
					this.SendPropertyChanged("music");
					this.OnmusicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula_auana", DbType="Int")]
		public System.Nullable<int> hula_auana
		{
			get
			{
				return this._hula_auana;
			}
			set
			{
				if ((this._hula_auana != value))
				{
					this.Onhula_auanaChanging(value);
					this.SendPropertyChanging();
					this._hula_auana = value;
					this.SendPropertyChanged("hula_auana");
					this.Onhula_auanaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula_auana_deduction", DbType="Int")]
		public System.Nullable<int> hula_auana_deduction
		{
			get
			{
				return this._hula_auana_deduction;
			}
			set
			{
				if ((this._hula_auana_deduction != value))
				{
					this.Onhula_auana_deductionChanging(value);
					this.SendPropertyChanging();
					this._hula_auana_deduction = value;
					this.SendPropertyChanged("hula_auana_deduction");
					this.Onhula_auana_deductionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula_kahiko", DbType="Int")]
		public System.Nullable<int> hula_kahiko
		{
			get
			{
				return this._hula_kahiko;
			}
			set
			{
				if ((this._hula_kahiko != value))
				{
					this.Onhula_kahikoChanging(value);
					this.SendPropertyChanging();
					this._hula_kahiko = value;
					this.SendPropertyChanged("hula_kahiko");
					this.Onhula_kahikoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula_kahiko_deduction", DbType="Int")]
		public System.Nullable<int> hula_kahiko_deduction
		{
			get
			{
				return this._hula_kahiko_deduction;
			}
			set
			{
				if ((this._hula_kahiko_deduction != value))
				{
					this.Onhula_kahiko_deductionChanging(value);
					this.SendPropertyChanging();
					this._hula_kahiko_deduction = value;
					this.SendPropertyChanged("hula_kahiko_deduction");
					this.Onhula_kahiko_deductionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula_palua", DbType="Int")]
		public System.Nullable<int> hula_palua
		{
			get
			{
				return this._hula_palua;
			}
			set
			{
				if ((this._hula_palua != value))
				{
					this.Onhula_paluaChanging(value);
					this.SendPropertyChanging();
					this._hula_palua = value;
					this.SendPropertyChanged("hula_palua");
					this.Onhula_paluaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula_palua_deduction", DbType="Int")]
		public System.Nullable<int> hula_palua_deduction
		{
			get
			{
				return this._hula_palua_deduction;
			}
			set
			{
				if ((this._hula_palua_deduction != value))
				{
					this.Onhula_palua_deductionChanging(value);
					this.SendPropertyChanging();
					this._hula_palua_deduction = value;
					this.SendPropertyChanged("hula_palua_deduction");
					this.Onhula_palua_deductionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costume_auana", DbType="Int")]
		public System.Nullable<int> costume_auana
		{
			get
			{
				return this._costume_auana;
			}
			set
			{
				if ((this._costume_auana != value))
				{
					this.Oncostume_auanaChanging(value);
					this.SendPropertyChanging();
					this._costume_auana = value;
					this.SendPropertyChanged("costume_auana");
					this.Oncostume_auanaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costume_kahiko", DbType="Int")]
		public System.Nullable<int> costume_kahiko
		{
			get
			{
				return this._costume_kahiko;
			}
			set
			{
				if ((this._costume_kahiko != value))
				{
					this.Oncostume_kahikoChanging(value);
					this.SendPropertyChanging();
					this._costume_kahiko = value;
					this.SendPropertyChanged("costume_kahiko");
					this.Oncostume_kahikoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costume_palua", DbType="Int")]
		public System.Nullable<int> costume_palua
		{
			get
			{
				return this._costume_palua;
			}
			set
			{
				if ((this._costume_palua != value))
				{
					this.Oncostume_paluaChanging(value);
					this.SendPropertyChanging();
					this._costume_palua = value;
					this.SendPropertyChanged("costume_palua");
					this.Oncostume_paluaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_out_of_order_deduction", DbType="Int")]
		public System.Nullable<int> out_of_order_deduction
		{
			get
			{
				return this._out_of_order_deduction;
			}
			set
			{
				if ((this._out_of_order_deduction != value))
				{
					this.Onout_of_order_deductionChanging(value);
					this.SendPropertyChanging();
					this._out_of_order_deduction = value;
					this.SendPropertyChanged("out_of_order_deduction");
					this.Onout_of_order_deductionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contestant_MasterScore", Storage="_Contestant", ThisKey="contestant_id", OtherKey="id", IsForeignKey=true)]
		public Contestant Contestant
		{
			get
			{
				return this._Contestant.Entity;
			}
			set
			{
				Contestant previousValue = this._Contestant.Entity;
				if (((previousValue != value) 
							|| (this._Contestant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Contestant.Entity = null;
						previousValue.MasterScores.Remove(this);
					}
					this._Contestant.Entity = value;
					if ((value != null))
					{
						value.MasterScores.Add(this);
						this._contestant_id = value.id;
					}
					else
					{
						this._contestant_id = default(int);
					}
					this.SendPropertyChanged("Contestant");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Award")]
	public partial class Award : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public Award()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contestant")]
	public partial class Contestant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _age_id;
		
		private int _gender_id;
		
		private int _division_id;
		
		private int _halau_id;
		
		private int _kumu_id;
		
		private string _full_name;
		
		private System.DateTime _entry_date;
		
		private System.Nullable<int> _entry_num_fri;
		
		private System.Nullable<int> _entry_num_sat;
		
		private EntitySet<MasterScore> _MasterScores;
		
		private EntitySet<JudgeScore> _JudgeScores;
		
		private EntityRef<Age> _Age;
		
		private EntityRef<Division> _Division;
		
		private EntityRef<Gender> _Gender;
		
		private EntityRef<Halau> _Halau;
		
		private EntityRef<Kumu> _Kumu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onage_idChanging(int value);
    partial void Onage_idChanged();
    partial void Ongender_idChanging(int value);
    partial void Ongender_idChanged();
    partial void Ondivision_idChanging(int value);
    partial void Ondivision_idChanged();
    partial void Onhalau_idChanging(int value);
    partial void Onhalau_idChanged();
    partial void Onkumu_idChanging(int value);
    partial void Onkumu_idChanged();
    partial void Onfull_nameChanging(string value);
    partial void Onfull_nameChanged();
    partial void Onentry_dateChanging(System.DateTime value);
    partial void Onentry_dateChanged();
    partial void Onentry_num_friChanging(System.Nullable<int> value);
    partial void Onentry_num_friChanged();
    partial void Onentry_num_satChanging(System.Nullable<int> value);
    partial void Onentry_num_satChanged();
    #endregion
		
		public Contestant()
		{
			this._MasterScores = new EntitySet<MasterScore>(new Action<MasterScore>(this.attach_MasterScores), new Action<MasterScore>(this.detach_MasterScores));
			this._JudgeScores = new EntitySet<JudgeScore>(new Action<JudgeScore>(this.attach_JudgeScores), new Action<JudgeScore>(this.detach_JudgeScores));
			this._Age = default(EntityRef<Age>);
			this._Division = default(EntityRef<Division>);
			this._Gender = default(EntityRef<Gender>);
			this._Halau = default(EntityRef<Halau>);
			this._Kumu = default(EntityRef<Kumu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age_id", DbType="Int NOT NULL")]
		public int age_id
		{
			get
			{
				return this._age_id;
			}
			set
			{
				if ((this._age_id != value))
				{
					if (this._Age.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onage_idChanging(value);
					this.SendPropertyChanging();
					this._age_id = value;
					this.SendPropertyChanged("age_id");
					this.Onage_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender_id", DbType="Int NOT NULL")]
		public int gender_id
		{
			get
			{
				return this._gender_id;
			}
			set
			{
				if ((this._gender_id != value))
				{
					if (this._Gender.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongender_idChanging(value);
					this.SendPropertyChanging();
					this._gender_id = value;
					this.SendPropertyChanged("gender_id");
					this.Ongender_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_division_id", DbType="Int NOT NULL")]
		public int division_id
		{
			get
			{
				return this._division_id;
			}
			set
			{
				if ((this._division_id != value))
				{
					if (this._Division.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondivision_idChanging(value);
					this.SendPropertyChanging();
					this._division_id = value;
					this.SendPropertyChanged("division_id");
					this.Ondivision_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_halau_id", DbType="Int NOT NULL")]
		public int halau_id
		{
			get
			{
				return this._halau_id;
			}
			set
			{
				if ((this._halau_id != value))
				{
					if (this._Halau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onhalau_idChanging(value);
					this.SendPropertyChanging();
					this._halau_id = value;
					this.SendPropertyChanged("halau_id");
					this.Onhalau_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumu_id", DbType="Int NOT NULL")]
		public int kumu_id
		{
			get
			{
				return this._kumu_id;
			}
			set
			{
				if ((this._kumu_id != value))
				{
					if (this._Kumu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkumu_idChanging(value);
					this.SendPropertyChanging();
					this._kumu_id = value;
					this.SendPropertyChanged("kumu_id");
					this.Onkumu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string full_name
		{
			get
			{
				return this._full_name;
			}
			set
			{
				if ((this._full_name != value))
				{
					this.Onfull_nameChanging(value);
					this.SendPropertyChanging();
					this._full_name = value;
					this.SendPropertyChanged("full_name");
					this.Onfull_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entry_date", DbType="Date NOT NULL")]
		public System.DateTime entry_date
		{
			get
			{
				return this._entry_date;
			}
			set
			{
				if ((this._entry_date != value))
				{
					this.Onentry_dateChanging(value);
					this.SendPropertyChanging();
					this._entry_date = value;
					this.SendPropertyChanged("entry_date");
					this.Onentry_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entry_num_fri", DbType="Int")]
		public System.Nullable<int> entry_num_fri
		{
			get
			{
				return this._entry_num_fri;
			}
			set
			{
				if ((this._entry_num_fri != value))
				{
					this.Onentry_num_friChanging(value);
					this.SendPropertyChanging();
					this._entry_num_fri = value;
					this.SendPropertyChanged("entry_num_fri");
					this.Onentry_num_friChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entry_num_sat", DbType="Int")]
		public System.Nullable<int> entry_num_sat
		{
			get
			{
				return this._entry_num_sat;
			}
			set
			{
				if ((this._entry_num_sat != value))
				{
					this.Onentry_num_satChanging(value);
					this.SendPropertyChanging();
					this._entry_num_sat = value;
					this.SendPropertyChanged("entry_num_sat");
					this.Onentry_num_satChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contestant_MasterScore", Storage="_MasterScores", ThisKey="id", OtherKey="contestant_id")]
		public EntitySet<MasterScore> MasterScores
		{
			get
			{
				return this._MasterScores;
			}
			set
			{
				this._MasterScores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contestant_JudgeScore", Storage="_JudgeScores", ThisKey="id", OtherKey="contestant_id")]
		public EntitySet<JudgeScore> JudgeScores
		{
			get
			{
				return this._JudgeScores;
			}
			set
			{
				this._JudgeScores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Age_Contestant", Storage="_Age", ThisKey="age_id", OtherKey="id", IsForeignKey=true)]
		public Age Age
		{
			get
			{
				return this._Age.Entity;
			}
			set
			{
				Age previousValue = this._Age.Entity;
				if (((previousValue != value) 
							|| (this._Age.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Age.Entity = null;
						previousValue.Contestants.Remove(this);
					}
					this._Age.Entity = value;
					if ((value != null))
					{
						value.Contestants.Add(this);
						this._age_id = value.id;
					}
					else
					{
						this._age_id = default(int);
					}
					this.SendPropertyChanged("Age");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Division_Contestant", Storage="_Division", ThisKey="division_id", OtherKey="id", IsForeignKey=true)]
		public Division Division
		{
			get
			{
				return this._Division.Entity;
			}
			set
			{
				Division previousValue = this._Division.Entity;
				if (((previousValue != value) 
							|| (this._Division.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Division.Entity = null;
						previousValue.Contestants.Remove(this);
					}
					this._Division.Entity = value;
					if ((value != null))
					{
						value.Contestants.Add(this);
						this._division_id = value.id;
					}
					else
					{
						this._division_id = default(int);
					}
					this.SendPropertyChanged("Division");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gender_Contestant", Storage="_Gender", ThisKey="gender_id", OtherKey="id", IsForeignKey=true)]
		public Gender Gender
		{
			get
			{
				return this._Gender.Entity;
			}
			set
			{
				Gender previousValue = this._Gender.Entity;
				if (((previousValue != value) 
							|| (this._Gender.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Gender.Entity = null;
						previousValue.Contestants.Remove(this);
					}
					this._Gender.Entity = value;
					if ((value != null))
					{
						value.Contestants.Add(this);
						this._gender_id = value.id;
					}
					else
					{
						this._gender_id = default(int);
					}
					this.SendPropertyChanged("Gender");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Halau_Contestant", Storage="_Halau", ThisKey="halau_id", OtherKey="id", IsForeignKey=true)]
		public Halau Halau
		{
			get
			{
				return this._Halau.Entity;
			}
			set
			{
				Halau previousValue = this._Halau.Entity;
				if (((previousValue != value) 
							|| (this._Halau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Halau.Entity = null;
						previousValue.Contestants.Remove(this);
					}
					this._Halau.Entity = value;
					if ((value != null))
					{
						value.Contestants.Add(this);
						this._halau_id = value.id;
					}
					else
					{
						this._halau_id = default(int);
					}
					this.SendPropertyChanged("Halau");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kumu_Contestant", Storage="_Kumu", ThisKey="kumu_id", OtherKey="id", IsForeignKey=true)]
		public Kumu Kumu
		{
			get
			{
				return this._Kumu.Entity;
			}
			set
			{
				Kumu previousValue = this._Kumu.Entity;
				if (((previousValue != value) 
							|| (this._Kumu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kumu.Entity = null;
						previousValue.Contestants.Remove(this);
					}
					this._Kumu.Entity = value;
					if ((value != null))
					{
						value.Contestants.Add(this);
						this._kumu_id = value.id;
					}
					else
					{
						this._kumu_id = default(int);
					}
					this.SendPropertyChanged("Kumu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MasterScores(MasterScore entity)
		{
			this.SendPropertyChanging();
			entity.Contestant = this;
		}
		
		private void detach_MasterScores(MasterScore entity)
		{
			this.SendPropertyChanging();
			entity.Contestant = null;
		}
		
		private void attach_JudgeScores(JudgeScore entity)
		{
			this.SendPropertyChanging();
			entity.Contestant = this;
		}
		
		private void detach_JudgeScores(JudgeScore entity)
		{
			this.SendPropertyChanging();
			entity.Contestant = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Division")]
	public partial class Division : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private EntitySet<Contestant> _Contestants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Division()
		{
			this._Contestants = new EntitySet<Contestant>(new Action<Contestant>(this.attach_Contestants), new Action<Contestant>(this.detach_Contestants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Division_Contestant", Storage="_Contestants", ThisKey="id", OtherKey="division_id")]
		public EntitySet<Contestant> Contestants
		{
			get
			{
				return this._Contestants;
			}
			set
			{
				this._Contestants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Division = this;
		}
		
		private void detach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Division = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gender")]
	public partial class Gender : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private EntitySet<Contestant> _Contestants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Gender()
		{
			this._Contestants = new EntitySet<Contestant>(new Action<Contestant>(this.attach_Contestants), new Action<Contestant>(this.detach_Contestants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gender_Contestant", Storage="_Contestants", ThisKey="id", OtherKey="gender_id")]
		public EntitySet<Contestant> Contestants
		{
			get
			{
				return this._Contestants;
			}
			set
			{
				this._Contestants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Gender = this;
		}
		
		private void detach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Gender = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Halau")]
	public partial class Halau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private EntitySet<Contestant> _Contestants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Halau()
		{
			this._Contestants = new EntitySet<Contestant>(new Action<Contestant>(this.attach_Contestants), new Action<Contestant>(this.detach_Contestants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Halau_Contestant", Storage="_Contestants", ThisKey="id", OtherKey="halau_id")]
		public EntitySet<Contestant> Contestants
		{
			get
			{
				return this._Contestants;
			}
			set
			{
				this._Contestants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Halau = this;
		}
		
		private void detach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Halau = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Judge")]
	public partial class Judge : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _full_name;
		
		private EntitySet<JudgeScore> _JudgeScores;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onfull_nameChanging(string value);
    partial void Onfull_nameChanged();
    #endregion
		
		public Judge()
		{
			this._JudgeScores = new EntitySet<JudgeScore>(new Action<JudgeScore>(this.attach_JudgeScores), new Action<JudgeScore>(this.detach_JudgeScores));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string full_name
		{
			get
			{
				return this._full_name;
			}
			set
			{
				if ((this._full_name != value))
				{
					this.Onfull_nameChanging(value);
					this.SendPropertyChanging();
					this._full_name = value;
					this.SendPropertyChanged("full_name");
					this.Onfull_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Judge_JudgeScore", Storage="_JudgeScores", ThisKey="id", OtherKey="judge_id")]
		public EntitySet<JudgeScore> JudgeScores
		{
			get
			{
				return this._JudgeScores;
			}
			set
			{
				this._JudgeScores.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_JudgeScores(JudgeScore entity)
		{
			this.SendPropertyChanging();
			entity.Judge = this;
		}
		
		private void detach_JudgeScores(JudgeScore entity)
		{
			this.SendPropertyChanging();
			entity.Judge = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JudgeScore")]
	public partial class JudgeScore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _contestant_id;
		
		private int _judge_id;
		
		private System.Nullable<int> _interview;
		
		private System.Nullable<int> _costume_auana;
		
		private System.Nullable<int> _costume_kahiko;
		
		private System.Nullable<int> _costume_palua;
		
		private System.Nullable<int> _hula_auana;
		
		private System.Nullable<int> _hula_kahiko;
		
		private System.Nullable<int> _hula_palua;
		
		private EntityRef<Contestant> _Contestant;
		
		private EntityRef<Judge> _Judge;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncontestant_idChanging(int value);
    partial void Oncontestant_idChanged();
    partial void Onjudge_idChanging(int value);
    partial void Onjudge_idChanged();
    partial void OninterviewChanging(System.Nullable<int> value);
    partial void OninterviewChanged();
    partial void Oncostume_auanaChanging(System.Nullable<int> value);
    partial void Oncostume_auanaChanged();
    partial void Oncostume_kahikoChanging(System.Nullable<int> value);
    partial void Oncostume_kahikoChanged();
    partial void Oncostume_paluaChanging(System.Nullable<int> value);
    partial void Oncostume_paluaChanged();
    partial void Onhula_auanaChanging(System.Nullable<int> value);
    partial void Onhula_auanaChanged();
    partial void Onhula_kahikoChanging(System.Nullable<int> value);
    partial void Onhula_kahikoChanged();
    partial void Onhula_paluaChanging(System.Nullable<int> value);
    partial void Onhula_paluaChanged();
    #endregion
		
		public JudgeScore()
		{
			this._Contestant = default(EntityRef<Contestant>);
			this._Judge = default(EntityRef<Judge>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contestant_id", DbType="Int NOT NULL")]
		public int contestant_id
		{
			get
			{
				return this._contestant_id;
			}
			set
			{
				if ((this._contestant_id != value))
				{
					if (this._Contestant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncontestant_idChanging(value);
					this.SendPropertyChanging();
					this._contestant_id = value;
					this.SendPropertyChanged("contestant_id");
					this.Oncontestant_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_judge_id", DbType="Int NOT NULL")]
		public int judge_id
		{
			get
			{
				return this._judge_id;
			}
			set
			{
				if ((this._judge_id != value))
				{
					if (this._Judge.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onjudge_idChanging(value);
					this.SendPropertyChanging();
					this._judge_id = value;
					this.SendPropertyChanged("judge_id");
					this.Onjudge_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_interview", DbType="Int")]
		public System.Nullable<int> interview
		{
			get
			{
				return this._interview;
			}
			set
			{
				if ((this._interview != value))
				{
					this.OninterviewChanging(value);
					this.SendPropertyChanging();
					this._interview = value;
					this.SendPropertyChanged("interview");
					this.OninterviewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costume_auana", DbType="Int")]
		public System.Nullable<int> costume_auana
		{
			get
			{
				return this._costume_auana;
			}
			set
			{
				if ((this._costume_auana != value))
				{
					this.Oncostume_auanaChanging(value);
					this.SendPropertyChanging();
					this._costume_auana = value;
					this.SendPropertyChanged("costume_auana");
					this.Oncostume_auanaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costume_kahiko", DbType="Int")]
		public System.Nullable<int> costume_kahiko
		{
			get
			{
				return this._costume_kahiko;
			}
			set
			{
				if ((this._costume_kahiko != value))
				{
					this.Oncostume_kahikoChanging(value);
					this.SendPropertyChanging();
					this._costume_kahiko = value;
					this.SendPropertyChanged("costume_kahiko");
					this.Oncostume_kahikoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costume_palua", DbType="Int")]
		public System.Nullable<int> costume_palua
		{
			get
			{
				return this._costume_palua;
			}
			set
			{
				if ((this._costume_palua != value))
				{
					this.Oncostume_paluaChanging(value);
					this.SendPropertyChanging();
					this._costume_palua = value;
					this.SendPropertyChanged("costume_palua");
					this.Oncostume_paluaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula_auana", DbType="Int")]
		public System.Nullable<int> hula_auana
		{
			get
			{
				return this._hula_auana;
			}
			set
			{
				if ((this._hula_auana != value))
				{
					this.Onhula_auanaChanging(value);
					this.SendPropertyChanging();
					this._hula_auana = value;
					this.SendPropertyChanged("hula_auana");
					this.Onhula_auanaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula_kahiko", DbType="Int")]
		public System.Nullable<int> hula_kahiko
		{
			get
			{
				return this._hula_kahiko;
			}
			set
			{
				if ((this._hula_kahiko != value))
				{
					this.Onhula_kahikoChanging(value);
					this.SendPropertyChanging();
					this._hula_kahiko = value;
					this.SendPropertyChanged("hula_kahiko");
					this.Onhula_kahikoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula_palua", DbType="Int")]
		public System.Nullable<int> hula_palua
		{
			get
			{
				return this._hula_palua;
			}
			set
			{
				if ((this._hula_palua != value))
				{
					this.Onhula_paluaChanging(value);
					this.SendPropertyChanging();
					this._hula_palua = value;
					this.SendPropertyChanged("hula_palua");
					this.Onhula_paluaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contestant_JudgeScore", Storage="_Contestant", ThisKey="contestant_id", OtherKey="id", IsForeignKey=true)]
		public Contestant Contestant
		{
			get
			{
				return this._Contestant.Entity;
			}
			set
			{
				Contestant previousValue = this._Contestant.Entity;
				if (((previousValue != value) 
							|| (this._Contestant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Contestant.Entity = null;
						previousValue.JudgeScores.Remove(this);
					}
					this._Contestant.Entity = value;
					if ((value != null))
					{
						value.JudgeScores.Add(this);
						this._contestant_id = value.id;
					}
					else
					{
						this._contestant_id = default(int);
					}
					this.SendPropertyChanged("Contestant");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Judge_JudgeScore", Storage="_Judge", ThisKey="judge_id", OtherKey="id", IsForeignKey=true)]
		public Judge Judge
		{
			get
			{
				return this._Judge.Entity;
			}
			set
			{
				Judge previousValue = this._Judge.Entity;
				if (((previousValue != value) 
							|| (this._Judge.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Judge.Entity = null;
						previousValue.JudgeScores.Remove(this);
					}
					this._Judge.Entity = value;
					if ((value != null))
					{
						value.JudgeScores.Add(this);
						this._judge_id = value.id;
					}
					else
					{
						this._judge_id = default(int);
					}
					this.SendPropertyChanged("Judge");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kumu")]
	public partial class Kumu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _full_name;
		
		private EntitySet<Contestant> _Contestants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onfull_nameChanging(string value);
    partial void Onfull_nameChanged();
    #endregion
		
		public Kumu()
		{
			this._Contestants = new EntitySet<Contestant>(new Action<Contestant>(this.attach_Contestants), new Action<Contestant>(this.detach_Contestants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string full_name
		{
			get
			{
				return this._full_name;
			}
			set
			{
				if ((this._full_name != value))
				{
					this.Onfull_nameChanging(value);
					this.SendPropertyChanging();
					this._full_name = value;
					this.SendPropertyChanged("full_name");
					this.Onfull_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kumu_Contestant", Storage="_Contestants", ThisKey="id", OtherKey="kumu_id")]
		public EntitySet<Contestant> Contestants
		{
			get
			{
				return this._Contestants;
			}
			set
			{
				this._Contestants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Kumu = this;
		}
		
		private void detach_Contestants(Contestant entity)
		{
			this.SendPropertyChanging();
			entity.Kumu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_BreakingScore")]
	public partial class vw_BreakingScore
	{
		
		private int _contestant_id;
		
		private System.Nullable<int> _interview_tie;
		
		private System.Nullable<int> _costume_auana_tie;
		
		private System.Nullable<int> _costume_kahiko_tie;
		
		private System.Nullable<int> _costume_palua_tie;
		
		private System.Nullable<int> _hula_auana_tie;
		
		private System.Nullable<int> _hula_kahiko_tie;
		
		private System.Nullable<int> _hula_palua_tie;
		
		public vw_BreakingScore()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contestant_id", DbType="Int NOT NULL")]
		public int contestant_id
		{
			get
			{
				return this._contestant_id;
			}
			set
			{
				if ((this._contestant_id != value))
				{
					this._contestant_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_interview_tie", DbType="Int")]
		public System.Nullable<int> interview_tie
		{
			get
			{
				return this._interview_tie;
			}
			set
			{
				if ((this._interview_tie != value))
				{
					this._interview_tie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costume_auana_tie", DbType="Int")]
		public System.Nullable<int> costume_auana_tie
		{
			get
			{
				return this._costume_auana_tie;
			}
			set
			{
				if ((this._costume_auana_tie != value))
				{
					this._costume_auana_tie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costume_kahiko_tie", DbType="Int")]
		public System.Nullable<int> costume_kahiko_tie
		{
			get
			{
				return this._costume_kahiko_tie;
			}
			set
			{
				if ((this._costume_kahiko_tie != value))
				{
					this._costume_kahiko_tie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costume_palua_tie", DbType="Int")]
		public System.Nullable<int> costume_palua_tie
		{
			get
			{
				return this._costume_palua_tie;
			}
			set
			{
				if ((this._costume_palua_tie != value))
				{
					this._costume_palua_tie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula_auana_tie", DbType="Int")]
		public System.Nullable<int> hula_auana_tie
		{
			get
			{
				return this._hula_auana_tie;
			}
			set
			{
				if ((this._hula_auana_tie != value))
				{
					this._hula_auana_tie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula_kahiko_tie", DbType="Int")]
		public System.Nullable<int> hula_kahiko_tie
		{
			get
			{
				return this._hula_kahiko_tie;
			}
			set
			{
				if ((this._hula_kahiko_tie != value))
				{
					this._hula_kahiko_tie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula_palua_tie", DbType="Int")]
		public System.Nullable<int> hula_palua_tie
		{
			get
			{
				return this._hula_palua_tie;
			}
			set
			{
				if ((this._hula_palua_tie != value))
				{
					this._hula_palua_tie = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_ContestantDetails")]
	public partial class vw_ContestantDetail
	{
		
		private int _id;
		
		private string _full_name;
		
		private string _age_name;
		
		private string _gender_name;
		
		private string _division_name;
		
		private string _halau_name;
		
		private string _kumu_name;
		
		private System.DateTime _entry_date;
		
		private System.Nullable<int> _entry_num_fri;
		
		private System.Nullable<int> _entry_num_sat;
		
		public vw_ContestantDetail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string full_name
		{
			get
			{
				return this._full_name;
			}
			set
			{
				if ((this._full_name != value))
				{
					this._full_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string age_name
		{
			get
			{
				return this._age_name;
			}
			set
			{
				if ((this._age_name != value))
				{
					this._age_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string gender_name
		{
			get
			{
				return this._gender_name;
			}
			set
			{
				if ((this._gender_name != value))
				{
					this._gender_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_division_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string division_name
		{
			get
			{
				return this._division_name;
			}
			set
			{
				if ((this._division_name != value))
				{
					this._division_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_halau_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string halau_name
		{
			get
			{
				return this._halau_name;
			}
			set
			{
				if ((this._halau_name != value))
				{
					this._halau_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumu_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string kumu_name
		{
			get
			{
				return this._kumu_name;
			}
			set
			{
				if ((this._kumu_name != value))
				{
					this._kumu_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entry_date", DbType="Date NOT NULL")]
		public System.DateTime entry_date
		{
			get
			{
				return this._entry_date;
			}
			set
			{
				if ((this._entry_date != value))
				{
					this._entry_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entry_num_fri", DbType="Int")]
		public System.Nullable<int> entry_num_fri
		{
			get
			{
				return this._entry_num_fri;
			}
			set
			{
				if ((this._entry_num_fri != value))
				{
					this._entry_num_fri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entry_num_sat", DbType="Int")]
		public System.Nullable<int> entry_num_sat
		{
			get
			{
				return this._entry_num_sat;
			}
			set
			{
				if ((this._entry_num_sat != value))
				{
					this._entry_num_sat = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_BreakingScoreNet")]
	public partial class vw_BreakingScoreNet
	{
		
		private int _contestant_id;
		
		private int _palapala;
		
		private System.Nullable<int> _interview_tie;
		
		private System.Nullable<decimal> _oli;
		
		private System.Nullable<int> _hula_auana_net;
		
		private System.Nullable<int> _hula_kahiko_net;
		
		private System.Nullable<int> _hula_palua_net;
		
		private System.Nullable<int> _out_of_order_deduction;
		
		public vw_BreakingScoreNet()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contestant_id", DbType="Int NOT NULL")]
		public int contestant_id
		{
			get
			{
				return this._contestant_id;
			}
			set
			{
				if ((this._contestant_id != value))
				{
					this._contestant_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_palapala", DbType="Int NOT NULL")]
		public int palapala
		{
			get
			{
				return this._palapala;
			}
			set
			{
				if ((this._palapala != value))
				{
					this._palapala = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_interview_tie", DbType="Int")]
		public System.Nullable<int> interview_tie
		{
			get
			{
				return this._interview_tie;
			}
			set
			{
				if ((this._interview_tie != value))
				{
					this._interview_tie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oli", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> oli
		{
			get
			{
				return this._oli;
			}
			set
			{
				if ((this._oli != value))
				{
					this._oli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula_auana_net", DbType="Int")]
		public System.Nullable<int> hula_auana_net
		{
			get
			{
				return this._hula_auana_net;
			}
			set
			{
				if ((this._hula_auana_net != value))
				{
					this._hula_auana_net = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula_kahiko_net", DbType="Int")]
		public System.Nullable<int> hula_kahiko_net
		{
			get
			{
				return this._hula_kahiko_net;
			}
			set
			{
				if ((this._hula_kahiko_net != value))
				{
					this._hula_kahiko_net = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hula_palua_net", DbType="Int")]
		public System.Nullable<int> hula_palua_net
		{
			get
			{
				return this._hula_palua_net;
			}
			set
			{
				if ((this._hula_palua_net != value))
				{
					this._hula_palua_net = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_out_of_order_deduction", DbType="Int")]
		public System.Nullable<int> out_of_order_deduction
		{
			get
			{
				return this._out_of_order_deduction;
			}
			set
			{
				if ((this._out_of_order_deduction != value))
				{
					this._out_of_order_deduction = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_MasterScoreDetails")]
	public partial class vw_MasterScoreDetail
	{
		
		private int _id;
		
		private System.Nullable<int> _entry_num_fri;
		
		private System.Nullable<int> _entry_num_sat;
		
		private string _full_name;
		
		private string _age_name;
		
		private string _gender_name;
		
		private string _division_name;
		
		private System.Nullable<int> _interview;
		
		private System.Nullable<int> _interview_tie;
		
		private System.Nullable<decimal> _overall_score;
		
		private System.Nullable<decimal> _overall_break_score;
		
		private System.Nullable<int> _music;
		
		private string _halau_name;
		
		private string _kumu_name;
		
		private System.DateTime _entry_date;
		
		public vw_MasterScoreDetail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entry_num_fri", DbType="Int")]
		public System.Nullable<int> entry_num_fri
		{
			get
			{
				return this._entry_num_fri;
			}
			set
			{
				if ((this._entry_num_fri != value))
				{
					this._entry_num_fri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entry_num_sat", DbType="Int")]
		public System.Nullable<int> entry_num_sat
		{
			get
			{
				return this._entry_num_sat;
			}
			set
			{
				if ((this._entry_num_sat != value))
				{
					this._entry_num_sat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string full_name
		{
			get
			{
				return this._full_name;
			}
			set
			{
				if ((this._full_name != value))
				{
					this._full_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string age_name
		{
			get
			{
				return this._age_name;
			}
			set
			{
				if ((this._age_name != value))
				{
					this._age_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string gender_name
		{
			get
			{
				return this._gender_name;
			}
			set
			{
				if ((this._gender_name != value))
				{
					this._gender_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_division_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string division_name
		{
			get
			{
				return this._division_name;
			}
			set
			{
				if ((this._division_name != value))
				{
					this._division_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_interview", DbType="Int")]
		public System.Nullable<int> interview
		{
			get
			{
				return this._interview;
			}
			set
			{
				if ((this._interview != value))
				{
					this._interview = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_interview_tie", DbType="Int")]
		public System.Nullable<int> interview_tie
		{
			get
			{
				return this._interview_tie;
			}
			set
			{
				if ((this._interview_tie != value))
				{
					this._interview_tie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overall_score", DbType="Decimal(24,3)")]
		public System.Nullable<decimal> overall_score
		{
			get
			{
				return this._overall_score;
			}
			set
			{
				if ((this._overall_score != value))
				{
					this._overall_score = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overall_break_score", DbType="Decimal(22,3)")]
		public System.Nullable<decimal> overall_break_score
		{
			get
			{
				return this._overall_break_score;
			}
			set
			{
				if ((this._overall_break_score != value))
				{
					this._overall_break_score = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_music", DbType="Int")]
		public System.Nullable<int> music
		{
			get
			{
				return this._music;
			}
			set
			{
				if ((this._music != value))
				{
					this._music = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_halau_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string halau_name
		{
			get
			{
				return this._halau_name;
			}
			set
			{
				if ((this._halau_name != value))
				{
					this._halau_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumu_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string kumu_name
		{
			get
			{
				return this._kumu_name;
			}
			set
			{
				if ((this._kumu_name != value))
				{
					this._kumu_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entry_date", DbType="Date NOT NULL")]
		public System.DateTime entry_date
		{
			get
			{
				return this._entry_date;
			}
			set
			{
				if ((this._entry_date != value))
				{
					this._entry_date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_OverallBreakingScore")]
	public partial class vw_OverallBreakingScore
	{
		
		private int _contestant_id;
		
		private System.Nullable<int> _combined_hula_score;
		
		private System.Nullable<decimal> _overall_break_score;
		
		public vw_OverallBreakingScore()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contestant_id", DbType="Int NOT NULL")]
		public int contestant_id
		{
			get
			{
				return this._contestant_id;
			}
			set
			{
				if ((this._contestant_id != value))
				{
					this._contestant_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_combined_hula_score", DbType="Int")]
		public System.Nullable<int> combined_hula_score
		{
			get
			{
				return this._combined_hula_score;
			}
			set
			{
				if ((this._combined_hula_score != value))
				{
					this._combined_hula_score = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overall_break_score", DbType="Decimal(22,3)")]
		public System.Nullable<decimal> overall_break_score
		{
			get
			{
				return this._overall_break_score;
			}
			set
			{
				if ((this._overall_break_score != value))
				{
					this._overall_break_score = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_OverallScore")]
	public partial class vw_OverallScore
	{
		
		private int _contestant_id;
		
		private System.Nullable<int> _interview;
		
		private System.Nullable<int> _interview_tie;
		
		private System.Nullable<decimal> _overall_score;
		
		private System.Nullable<decimal> _overall_break_score;
		
		private int _music;
		
		private System.Nullable<int> _combined_hula_score;
		
		public vw_OverallScore()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contestant_id", DbType="Int NOT NULL")]
		public int contestant_id
		{
			get
			{
				return this._contestant_id;
			}
			set
			{
				if ((this._contestant_id != value))
				{
					this._contestant_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_interview", DbType="Int")]
		public System.Nullable<int> interview
		{
			get
			{
				return this._interview;
			}
			set
			{
				if ((this._interview != value))
				{
					this._interview = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_interview_tie", DbType="Int")]
		public System.Nullable<int> interview_tie
		{
			get
			{
				return this._interview_tie;
			}
			set
			{
				if ((this._interview_tie != value))
				{
					this._interview_tie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overall_score", DbType="Decimal(24,3)")]
		public System.Nullable<decimal> overall_score
		{
			get
			{
				return this._overall_score;
			}
			set
			{
				if ((this._overall_score != value))
				{
					this._overall_score = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overall_break_score", DbType="Decimal(22,3)")]
		public System.Nullable<decimal> overall_break_score
		{
			get
			{
				return this._overall_break_score;
			}
			set
			{
				if ((this._overall_break_score != value))
				{
					this._overall_break_score = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_music", DbType="Int NOT NULL")]
		public int music
		{
			get
			{
				return this._music;
			}
			set
			{
				if ((this._music != value))
				{
					this._music = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_combined_hula_score", DbType="Int")]
		public System.Nullable<int> combined_hula_score
		{
			get
			{
				return this._combined_hula_score;
			}
			set
			{
				if ((this._combined_hula_score != value))
				{
					this._combined_hula_score = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
